resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d673b92f2a2d9354d102514d0a0fa74f8248b14a/snapshot.yaml

packages:
- .

extra-deps:
- git: git@github.com:input-output-hk/goblins.git
  commit: 6ea969b31c2bbaa7ba78b8e83b53a36bedfae10e

- git: git@github.com:input-output-hk/cardano-ledger-specs.git
  commit: 67445f63728ad4eeb8c6259bc29373e48f959eec
  subdirs:
    - byron/chain/executable-spec
    - byron/ledger/executable-spec
    - byron/semantics/executable-spec

- bimap-0.4.0
- gray-code-0.3.1
- moo-1.2
- Unique-0.4.7.6
