resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d673b92f2a2d9354d102514d0a0fa74f8248b14a/snapshot.yaml

packages:
- .

extra-deps:
- git: git@github.com:input-output-hk/goblins.git
  commit: cf133ee9fb5b6ae0fbb4c0ee2e912d9bc3a16a7f

- git: git@github.com:input-output-hk/cardano-ledger-specs.git
  commit: 354b97a16510ffba43677100cec7b7333fd3bd02
  subdirs:
    - byron/chain/executable-spec
    - byron/ledger/executable-spec
    - byron/semantics/executable-spec

- bimap-0.4.0
- gray-code-0.3.1
- moo-1.2
- Unique-0.4.7.6
